name: CI

on: [pull_request] # we want the workflow to trigger on commits to PRs only

jobs: # each workflow consists of 1+ jobs; by default, all jobs run in parallel
  lint: # job name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run linter
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run build checks
        run: npm run prepare

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run unit tests
        run: npm run test
